apiVersion: v1
kind: Service
metadata:
  name: app2-httpd
  namespace: default
  labels:
    app: app2-httpd
  annotations:
    description: "Service to expose app2-httpd deployment"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app: app2-httpd
  sessionAffinity: None
