apiVersion: v1
kind: Service
metadata:
  name: nginx2
  namespace: cxb-aznginx-pre
  labels:
    app: nginx2
  annotations:
    description: "Service to expose nginx2 deployment"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app: app1-nginx
  sessionAffinity: None
